name: Deploy app


on:
  push:
    branches:
       -main

jobs:
  build-and-deploy
  runs-on: ubuntu-latest
  steps:
  -names: Checkout
  uses: actions/checkout@v1

  -nmae: Configuration AWS Credentials
   uses: aws-actions/configure-aws-credentials@v1
   with: 
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
      aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      aws-region: us-east-1

  -name: Deploy static site S3 bucket
   run: aws s3 sync . s3://connect-git-aws --delete
  
  
